[package]
name = "distributed-adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.19.0"
rand = "0.8.4"
rayon = "1.5.1"
num_cpus = "1.14.0"
clap = "3.2.25"
